services:
- postgresql
before_script:
- psql -c 'create database fit_test;' -U postgres
language: ruby
rvm:
- 2.3
- jruby
- rbx-2

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version

before_install:
- openssl aes-256-cbc -K $encrypted_954526e24b10_key -iv $encrypted_954526e24b10_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib

- gcloud auth activate-service-account --key-file client_secrets.json
