services:
- postgresql
before_script:
- psql -c 'create database fit_test;' -U postgres
language: ruby
rvm:
- 2.3
- jruby
- rbx-2
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIAL=~/google_application_credential.json
    - CLIENT_SECRETS =~/client_secrets.json
    