services:
- postgresql
before_script:
- psql -c 'create database fit_test;' -U postgres
language: ruby
script:
- bundle exec rake rspec
rvm:
- 2.3.1
- jruby
- rbx-2
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_954526e24b10_key -iv $encrypted_954526e24b10_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json

before_deploy:
- gem install mime-types -v 2.6.2
- gem install rack -v '2.0.3'
- gem install nio4r -v '2.1.0'