services:
- postgresql
before_script:
- psql -c 'create database fit_test;' -U postgres
language: ruby
rvm:
- 2.3
- jruby
- rbx-2
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1


before_install:
  # Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    ruby scripts/fetch_gae_sdk.rb $(dirname "${GAE_PYTHONPATH}");
  fi


- openssl aes-256-cbc -K $encrypted_954526e24b10_key -iv $encrypted_954526e24b10_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc

- tar -xzf credentials.tar.gz
- mkdir -p lib

- gcloud auth activate-service-account --key-file client_secrets.json
