services:
- postgresql
before_script:
- psql -c 'create database fit_test;' -U postgres
language: ruby
rvm:
- 2.3
- jruby
- rbx-2
before_install:
- gcloud auth activate-service-account --key-file client_secrets.json
